### ISSUE TITLE
timeout sur requetes onglet 3 et 4 de la FIC ou getProprietaire

### ISSUE THREAD

**Issue by landryb** [georchestra/cadastrapp#174]
Je ne sais pas si c'est dépendant de notre infrastructure répartie ou de la taille de la DB cadastrapp (20g), mais certaines des requetes getFIC timeoutent après 60s (1 backend n'a pu répondre), et des fois des getCoProprietaire timeoutent avec un 504 après 120s (les 2 backends ont échoué->message d'erreur)

(il faut etre connecté pour ces appels..)
- https://ids.craig.fr/cadastrapp/services/getCoProprietaire?parcelle=2015630378000ZA0013 -> 504 au premier appel, ok après
- https://ids.craig.fr/cadastrapp/services/getFIC?parcelle=2015630378000ZA0013&onglet=3 -> timeout du 1er backend
- https://ids.craig.fr/cadastrapp/services/getFIC?parcelle=2015630378000ZA0013&onglet=4 -> pareil

Un pbm de taille d'index ou d'index manquant ? Je n'arrive pas a voir si c'est un pbm de reverse-proxy non lié a cadastrapp ou si c'est cadastrapp qui met trop de temps a répondre...

**Comment by landryb** [comment]
Quand une requete échoue sur un backend cadastrapp (et qu'il y'a donc fallback sur le 2e backend loadbalancé), on dirait bien que c'est cadastrapp qui ne répond pas:

pour un click sur 'fiche d'info parcellaire', ou la requete pour onglet=4 a échoué sur le 1er backend:

```
egrep -c '10:45.*Incoming request' /srv/log/tomcat/cadastrapp.log
7
egrep -c '10:45.*Sending response' /srv/log/tomcat/cadastrapp.log
6
$egrep 10:45.*cadastrapp /srv/log/tomcat/georchestra/access.log
78.220.184.92 - [06/May/2016:10:45:25 +0200] GET /cadastrapp/services/getParcelle?_dc=1462524325214&parcelle=2015630378000ZE0034 HTTP/1.0 200 178 17
78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getFIC?onglet=0&_dc=1462524338258&parcelle=2015630378000ZE0034 HTTP/1.0 200 212 17
78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getFIC?onglet=3&_dc=1462524338458&parcelle=2015630378000ZE0034 HTTP/1.0 200 55 23
78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getCoProprietaire?_dc=1462524338443&parcelle=2015630378000ZE0034 HTTP/1.0 200 2 131
78.220.184.92 - [06/May/2016:10:45:40 +0200] GET /cadastrapp/services/getFIC?onglet=2&_dc=1462524338304&parcelle=2015630378000ZE0034 HTTP/1.0 200 2 1838
78.220.184.92 - [06/May/2016:10:45:40 +0200] GET /cadastrapp/services/getFIC?onglet=1&_dc=1462524338441&parcelle=2015630378000ZE0034 HTTP/1.0 200 400 2108
```

pas de message d'erreur dans le log de la base de donnée, et j'ai beau chercher dans les logs tomcat je ne vois pas de traceback. Le security-proxy forwardant la requete a cadastrapp se prend un timeout après 60s.. et fallback sur le 2e backend, qui recoit la requete en double (!?) et y répond directement.

```
2016-05-06 10:46:38 security [ERROR] Exception occured when trying to connect to the remote host:
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
        at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:389)
        at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:338)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:313)
...
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)

```

Je creuse...

**Comment by pierrejego** [comment]
60 secondes ça fait long pour ne pas répondre, on en rediscute pendant le geocom.

A tout à l’heure

—
Pierre Jégo
Tél. : +33 (0)2 96 48 25 63

De : Landry Breuil [mailto:notifications@github.com]
Envoyé : vendredi 6 mai 2016 11:19
À : GFI-Informatique/cadastrapp cadastrapp@noreply.github.com
Objet : Re: [GFI-Informatique/cadastrapp] timeout sur requetes onglet 3 et 4 de la FIC ou getProprietaire (#174)

Quand une requete échoue sur un backend cadastrapp (et qu'il y'a donc fallback sur le 2e backend loadbalancé), on dirait bien que c'est cadastrapp qui ne répond pas:

pour un click sur 'fiche d'info parcellaire', ou la requete pour onglet=4 a échoué sur le 1er backend:

egrep -c '10:45.*Incoming request' /srv/log/tomcat/cadastrapp.log

7

egrep -c '10:45.*Sending response' /srv/log/tomcat/cadastrapp.log

6

$egrep 10:45.*cadastrapp /srv/log/tomcat/georchestra/access.log

78.220.184.92 - [06/May/2016:10:45:25 +0200] GET /cadastrapp/services/getParcelle?_dc=1462524325214&parcelle=2015630378000ZE0034 HTTP/1.0 200 178 17

78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getFIC?onglet=0&_dc=1462524338258&parcelle=2015630378000ZE0034 HTTP/1.0 200 212 17

78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getFIC?onglet=3&_dc=1462524338458&parcelle=2015630378000ZE0034 HTTP/1.0 200 55 23

78.220.184.92 - [06/May/2016:10:45:38 +0200] GET /cadastrapp/services/getCoProprietaire?_dc=1462524338443&parcelle=2015630378000ZE0034 HTTP/1.0 200 2 131

78.220.184.92 - [06/May/2016:10:45:40 +0200] GET /cadastrapp/services/getFIC?onglet=2&_dc=1462524338304&parcelle=2015630378000ZE0034 HTTP/1.0 200 2 1838

78.220.184.92 - [06/May/2016:10:45:40 +0200] GET /cadastrapp/services/getFIC?onglet=1&_dc=1462524338441&parcelle=2015630378000ZE0034 HTTP/1.0 200 400 2108

pas de message d'erreur dans le log de la base de donnée, et j'ai beau chercher dans les logs tomcat je ne vois pas de traceback. Le security-proxy forwardant la requete a cadastrapp se prend un timeout après 60s.. et fallback sur le 2e backend, qui recoit la requete en double (!?) et y répond directement.

2016-05-06 10:46:38 security [ERROR] Exception occured when trying to connect to the remote host:

org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe

```
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:389)

    at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)

    at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:338)

    at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:313)
```

...

Caused by: java.io.IOException: Broken pipe

```
    at sun.nio.ch.FileDispatcherImpl.write0(Native Method)

    at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)

    at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
```

Je creuse...

**Comment by MaelREBOUX** [comment]
@landryb @pierrejego : peut-on ferme ce ticket ?

**Comment by MaelREBOUX** [comment]
@landryb peut-on fermer ce ticket ?

**Comment by landryb** [comment]
Il y'avait 2 pbms distincts:
* manque d'indexes (corrigé dans #376 et #381)
* pbm de config du loadbalancing ici, que j'ai enfin pu débugguer/analyser/corriger. ouf.

**Comment by MaelREBOUX** [comment]
merci @landryb
