### ISSUE TITLE
minified file does not exist / no build procedure provided

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/cadastrapp#240]
https://github.com/georchestra/cadastrapp/blob/master/addons/cadastrapp/manifest.json#L2

**Comment by jusabatier** [comment]
In order to generate minified files, just have to launch "mvn clean install".
It build war in cadastrapp/target directory and minified JS files in the addon directory.
Probably it should be mentioned in the addon install procedure on the wiki that compilation is needed before copy addon to mapfishapp.

**Comment by fvanderbiest** [comment]
> In order to generate minified files, just have to launch "mvn clean install".

I should have had a look at this, indeed ...
Thanks.

**Comment by pmauduit** [comment]
It should be also interesting to generate a ZIP file with the required files for the mfapp addon, as it has been done for the urbanisme addon: 
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/pom.xml#L267-L284
and
https://github.com/sigrennesmetropole/addon_urbanisme/blob/master/addon-assembly.xml
