### ISSUE TITLE
Problème de recherche de propriétaires par code avec "+"

### ISSUE THREAD

**Issue by stous** [georchestra/cadastrapp#380]
Lorsque je pointe vers un fichier csv contenant plusieurs propriétaires 

> 

201743234S00252
201743234+00008
201743234B00489 

> 

 les parcelles du compte communal contenant un + ne sont pas sélectionnées, celles correspondant à la 1ere et dernière ligne le sont.

**Comment by landryb** [comment]
Dans le log coté serveur, on dirait qu'il découpe l'id de compte communal sur le + alors que le code dans https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L396 ne devrait pas, si je suis la logique..

Dans le log j'ai:
```
Parcelle from the csv file : 201743234S00252
Added to parcelle list : 201743234S00252
Parcelle from the csv file : 201743234
Added to parcelle list : 201743234
Parcelle from the csv file : 00008
Parcelle from the csv file : 201743234B00489
Added to parcelle list : 201743234B00489
```

**Comment by MaelREBOUX** [comment]
Hum bizarre ça me rappelle qqch. On a déjà rencontré ce problème il y a longtemps. Ou qqch approchant.

**Comment by MaelREBOUX** [comment]
Testé et je reproduis ce bogue.

**Comment by pierrejego** [comment]
En testant la fonctionnalité d'ajout de forme juridique, je me suis rendu compte que la recherche par compte communal avec un + ne fonctionnait pas non plus.

**Comment by pierrejego** [comment]
Pardon en fait si cela marche, mais il ne faut mettre que le dnupro et pas le numéro de comptecommunal vu qu'on ajout déjà le cgocommune dans la recherche

**Comment by pierrejego** [comment]
En passant en pas à pas, on voit que les informations reçues par le serveur sont érronées. Le + a été remplacé par un espace avant même de lire le fichier côté serveur.
Par contre si on a un caractère * , lui n'est pas remplacé par un espace.

**Comment by Gaetanbrl** [comment]
En encodant le + par %2B dans le fichier CSV chargé, on retrouve les bons résultats et les valeurs de comptecommunal avec un + ne sont pas ignorés.

**Comment by pierrejego** [comment]
Et via la recherche de comptecommunal (sans le CSV) ça fonctionne aussi ?
Peut être qu'un encodeURI sur le contenu CSV pourraît marcher, mais pour l'appel sans CSV normalement c'est déjà encodé

**Comment by Gaetanbrl** [comment]
En recherchant via l'onglet `compte propriétaire`, j'ai bien un résultat avec une valeur du type  `+00011`.

**Comment by Gaetanbrl** [comment]
Si je peux accéder au contenu (via le form d'envoi ou autre) alors ce sera potentiellement possible d'encoder les + avant l'envoi du submit (s'ils ne sont pas déjà remplacés par un espace).

**Comment by Gaetanbrl** [comment]
Une solution aurait pu être d'ajouter dans le fichier ParcelleController.js pour faire un remplacement des espaces par des +. Mais les espaces semblent être également des séparateur de numéro de compte, dans le cas ou par exemple quelqu'un upload un csv fait main avec la saisie des numéro dans une seule cellule, avec un espace comme séparateur...

Côté client, c'est un composant `<input type=file>` à la sauce ExtJs qui s'occupe d'envoyer par requête Ajax le CSV au serveur. La requête étant en POST pour faire un submit() de notre fichier, c'est malheureusement impossible d'observer ce qui est envoyé par la console du navigateur... donc impossible de vérifier si l'encodage du "+" saute via l'envoi à cet endroit.

Il est par contre possible d'observer à l'aide d'un FileReader() côté JavaScript, les données chargées dans l'élément <input>.
On voir alors que les + ne sont pas supprimés entre le choix du fichier et le chargement de ce fichier dans le `field upload`... ou alors il sont bien interprété par le javascript à la lecture et pas ensuite.

Vu sur [ce topic](https://codippa.com/encoding-symbol-in-ajax-request-jquery/) et avec FileReader(), vient alors l'idée de remplacer la méthode submit() du composant ExtJs afin de lire le fichier, d'encoder les "+" puis de refaire un CSV côté javascript à l'aide d'un Blob qui sera alors envoyer par requête Ajax au serveur en guise de FormData(). Les FormData sont normalement au même format qu'un submit() classique, donc idéal pour envoyer un fichier avec encodage "multipart/form-data" (ca tombe bien c'est qu'on veut).

Sauf que nous nous obtenons ainsi un header de type `Content-Type': ‘application/x-www-form-urlencoded`.
Ceci provoquant une erreur car ce n'est pas compatible, je force le header comme suit :
`**Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryUA3lGrHU3zGk4bem**`

En faisant cela, on obtient une erreur 500, le type MIME n'étant pas reconnaissable dans le headers.
`Caused by: java.io.IOException: Couldn't find MIME boundary: ------WebKitFormBoundaryV15abAYeJQ38jYwr`

Si vous avez des idées pour transmettre un CSV construit depuis le front à travers une requête Ajax je suis preneur... de toute autre idée également.

**Comment by pierrejego** [comment]
Au vu des problèmes que tu rencontres, il faut soit : 
- passer par du javascript sans ExtJs, mais tu risques de tomber sur d'autres problèmes de header http, de valeur de form etc....
- lire le csv côté client, pour envoyer la liste des comptes communaux dans une liste ou les + ne seront pas supprimés. Il te faudra créer un autre service côté serveur qui utilsera cette méthode https://github.com/georchestra/cadastrapp/blob/77b012afd9cd22f5d1e681c1e12d4696220d7340/cadastrapp/src/main/java/org/georchestra/cadastrapp/service/ParcelleController.java#L309
Pense à faire ce nouveau service en POST

Pour moi, il vaut mieux faire un nouveau service, et mettre en deprecated l'ancien avec une note vers cette issue.

par contre il faut faire des tests de tailles de fichiers, de validation de format de comptecommunal, etc côté client.

je me rend compte en analysant le code, qu'on a jamais limité le nombre d'élément dans le csv , il me semble qu'on en avait parlé il y a longtemps avec @MaelREBOUX . Il faudrait mettre un paramètre qui permette de limiter le nombre d'élément pris en compte dans le csv, ou d'indiquer qu'on ne le prend pas en compte car il dépasse les x éléments.

**Comment by MaelREBOUX** [comment]
C'est juste @pierrejego  ---> #457

**Comment by MaelREBOUX** [comment]
testé et approuvé
